version: '3'

services:
  web:
    build: .
    ports:
      - "5001:5001"
    depends_on:
      mysql:
        condition: service_started

  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: jovian_careers
    ports:
      - "3306:3306"
